diagram_fact(align, cell_22, "left").
diagram_fact(as, cell_10, "geometry").
diagram_fact(as, cell_11, "geometry").
diagram_fact(as, cell_12, "geometry").
diagram_fact(as, cell_13, "geometry").
diagram_fact(as, cell_14, "geometry").
diagram_fact(as, cell_15, "geometry").
diagram_fact(as, cell_16, "geometry").
diagram_fact(as, cell_17, "geometry").
diagram_fact(as, cell_18, "geometry").
diagram_fact(as, cell_19, "geometry").
diagram_fact(as, cell_20, "geometry").
diagram_fact(as, cell_21, "geometry").
diagram_fact(as, cell_22, "geometry").
diagram_fact(as, cell_6, "geometry").
diagram_fact(as, cell_7, "geometry").
diagram_fact(as, cell_8, "geometry").
diagram_fact(as, cell_9, "geometry").
diagram_fact(cell, cell_10, "").
diagram_fact(cell, cell_11, "").
diagram_fact(cell, cell_12, "").
diagram_fact(cell, cell_13, "").
diagram_fact(cell, cell_14, "").
diagram_fact(cell, cell_15, "").
diagram_fact(cell, cell_16, "").
diagram_fact(cell, cell_17, "").
diagram_fact(cell, cell_18, "").
diagram_fact(cell, cell_19, "").
diagram_fact(cell, cell_20, "").
diagram_fact(cell, cell_21, "").
diagram_fact(cell, cell_22, "").
diagram_fact(cell, cell_4, "").
diagram_fact(cell, cell_5, "").
diagram_fact(cell, cell_6, "").
diagram_fact(cell, cell_7, "").
diagram_fact(cell, cell_8, "").
diagram_fact(cell, cell_9, "").
diagram_fact(curved, cell_10, 1).
diagram_fact(curved, cell_6, 1).
diagram_fact(curved, cell_7, 1).
diagram_fact(curved, cell_8, 1).
diagram_fact(curved, cell_9, 1).
diagram_fact(diagram, diagram_1, "").
diagram_fact(edge, cell_10, 1).
diagram_fact(edge, cell_6, 1).
diagram_fact(edge, cell_7, 1).
diagram_fact(edge, cell_8, 1).
diagram_fact(edge, cell_9, 1).
diagram_fact(edgeStyle, cell_10, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_6, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_7, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_8, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_9, "orthogonalEdgeStyle").
diagram_fact(entryDx, cell_10, 0).
diagram_fact(entryDx, cell_8, 0).
diagram_fact(entryDx, cell_9, 0).
diagram_fact(entryDy, cell_10, 0).
diagram_fact(entryDy, cell_8, 0).
diagram_fact(entryDy, cell_9, 0).
diagram_fact(entryX, cell_10, 0.5).
diagram_fact(entryX, cell_8, 0.5).
diagram_fact(entryX, cell_9, 0.5).
diagram_fact(entryY, cell_10, 0).
diagram_fact(entryY, cell_8, 0).
diagram_fact(entryY, cell_9, 0).
diagram_fact(exitDx, cell_10, 0).
diagram_fact(exitDx, cell_6, 0).
diagram_fact(exitDx, cell_7, 0).
diagram_fact(exitDx, cell_8, 0).
diagram_fact(exitDx, cell_9, 0).
diagram_fact(exitDy, cell_10, 0).
diagram_fact(exitDy, cell_6, 0).
diagram_fact(exitDy, cell_7, 0).
diagram_fact(exitDy, cell_8, 0).
diagram_fact(exitDy, cell_9, 0).
diagram_fact(exitX, cell_10, 0.5).
diagram_fact(exitX, cell_6, 0.5).
diagram_fact(exitX, cell_7, 0.5).
diagram_fact(exitX, cell_8, 0.5).
diagram_fact(exitX, cell_9, 0.5).
diagram_fact(exitY, cell_10, 1).
diagram_fact(exitY, cell_6, 1).
diagram_fact(exitY, cell_7, 1).
diagram_fact(exitY, cell_8, 1).
diagram_fact(exitY, cell_9, 1).
diagram_fact(fillColor, cell_11, "#e1d5e7").
diagram_fact(fillColor, cell_12, "#f8cecc").
diagram_fact(fillColor, cell_13, "#f8cecc").
diagram_fact(fillColor, cell_14, "#f8cecc").
diagram_fact(fillColor, cell_15, "#f8cecc").
diagram_fact(fillColor, cell_16, "#f8cecc").
diagram_fact(fillColor, cell_17, "#f5f5f5").
diagram_fact(fillColor, cell_18, "#f5f5f5").
diagram_fact(fillColor, cell_19, "#f5f5f5").
diagram_fact(fillColor, cell_20, "#f5f5f5").
diagram_fact(fillColor, cell_21, "#f5f5f5").
diagram_fact(fontColor, cell_17, "#333333").
diagram_fact(fontColor, cell_18, "#333333").
diagram_fact(fontColor, cell_19, "#333333").
diagram_fact(fontColor, cell_20, "#333333").
diagram_fact(fontColor, cell_21, "#333333").
diagram_fact(height, cell_11, 90).
diagram_fact(height, cell_12, 90).
diagram_fact(height, cell_13, 90).
diagram_fact(height, cell_14, 90).
diagram_fact(height, cell_15, 90).
diagram_fact(height, cell_16, 90).
diagram_fact(height, cell_17, 40).
diagram_fact(height, cell_18, 25).
diagram_fact(height, cell_19, 30).
diagram_fact(height, cell_20, 30).
diagram_fact(height, cell_21, 40).
diagram_fact(height, cell_22, 190).
diagram_fact(html, cell_10, 1).
diagram_fact(html, cell_11, 1).
diagram_fact(html, cell_12, 1).
diagram_fact(html, cell_13, 1).
diagram_fact(html, cell_14, 1).
diagram_fact(html, cell_15, 1).
diagram_fact(html, cell_16, 1).
diagram_fact(html, cell_17, 1).
diagram_fact(html, cell_18, 1).
diagram_fact(html, cell_19, 1).
diagram_fact(html, cell_20, 1).
diagram_fact(html, cell_21, 1).
diagram_fact(html, cell_22, 1).
diagram_fact(html, cell_6, 1).
diagram_fact(html, cell_7, 1).
diagram_fact(html, cell_8, 1).
diagram_fact(html, cell_9, 1).
diagram_fact(jettySize, cell_10, "auto").
diagram_fact(jettySize, cell_6, "auto").
diagram_fact(jettySize, cell_7, "auto").
diagram_fact(jettySize, cell_8, "auto").
diagram_fact(jettySize, cell_9, "auto").
diagram_fact(mxGraphModel, mxGraphModel_2, mxGraphModel_2).
diagram_fact(name, diagram_1, "tree").
diagram_fact(orthogonalLoop, cell_10, 1).
diagram_fact(orthogonalLoop, cell_6, 1).
diagram_fact(orthogonalLoop, cell_7, 1).
diagram_fact(orthogonalLoop, cell_8, 1).
diagram_fact(orthogonalLoop, cell_9, 1).
diagram_fact(parent, cell_10, id_1).
diagram_fact(parent, cell_11, id_1).
diagram_fact(parent, cell_12, id_1).
diagram_fact(parent, cell_13, id_1).
diagram_fact(parent, cell_14, id_1).
diagram_fact(parent, cell_15, id_1).
diagram_fact(parent, cell_16, id_1).
diagram_fact(parent, cell_17, id_1).
diagram_fact(parent, cell_18, id_1).
diagram_fact(parent, cell_19, id_1).
diagram_fact(parent, cell_20, id_1).
diagram_fact(parent, cell_21, id_1).
diagram_fact(parent, cell_22, id_1).
diagram_fact(parent, cell_5, id_0).
diagram_fact(parent, cell_6, id_1).
diagram_fact(parent, cell_7, id_1).
diagram_fact(parent, cell_8, id_1).
diagram_fact(parent, cell_9, id_1).
diagram_fact(relative, cell_10, 1).
diagram_fact(relative, cell_6, 1).
diagram_fact(relative, cell_7, 1).
diagram_fact(relative, cell_8, 1).
diagram_fact(relative, cell_9, 1).
diagram_fact(root, root_3, root_3).
diagram_fact(rounded, cell_11, 1).
diagram_fact(rounded, cell_12, 1).
diagram_fact(rounded, cell_13, 1).
diagram_fact(rounded, cell_14, 1).
diagram_fact(rounded, cell_15, 1).
diagram_fact(rounded, cell_16, 1).
diagram_fact(rounded, cell_17, 0).
diagram_fact(rounded, cell_18, 0).
diagram_fact(rounded, cell_19, 0).
diagram_fact(rounded, cell_20, 0).
diagram_fact(rounded, cell_21, 0).
diagram_fact(rounded, cell_22, 0).
diagram_fact(source, cell_10, id_VDCRdWPJAwFapRl1d_3T__7).
diagram_fact(source, cell_6, id_VDCRdWPJAwFapRl1d_3T__7).
diagram_fact(source, cell_7, id_VDCRdWPJAwFapRl1d_3T__7).
diagram_fact(source, cell_8, id_VDCRdWPJAwFapRl1d_3T__7).
diagram_fact(source, cell_9, id_VDCRdWPJAwFapRl1d_3T__7).
diagram_fact(strokeColor, cell_11, "#9673a6").
diagram_fact(strokeColor, cell_12, "#b85450").
diagram_fact(strokeColor, cell_13, "#b85450").
diagram_fact(strokeColor, cell_14, "#b85450").
diagram_fact(strokeColor, cell_15, "#b85450").
diagram_fact(strokeColor, cell_16, "#b85450").
diagram_fact(strokeColor, cell_17, "#666666").
diagram_fact(strokeColor, cell_18, "#666666").
diagram_fact(strokeColor, cell_19, "#666666").
diagram_fact(strokeColor, cell_20, "#666666").
diagram_fact(strokeColor, cell_21, "#666666").
diagram_fact(synonym, cell_10, id_VDCRdWPJAwFapRl1d_3T__6).
diagram_fact(synonym, cell_11, id_VDCRdWPJAwFapRl1d_3T__7).
diagram_fact(synonym, cell_12, id_VDCRdWPJAwFapRl1d_3T__8).
diagram_fact(synonym, cell_13, id_VDCRdWPJAwFapRl1d_3T__9).
diagram_fact(synonym, cell_14, id_VDCRdWPJAwFapRl1d_3T__10).
diagram_fact(synonym, cell_15, id_VDCRdWPJAwFapRl1d_3T__11).
diagram_fact(synonym, cell_16, id_VDCRdWPJAwFapRl1d_3T__12).
diagram_fact(synonym, cell_17, id_VDCRdWPJAwFapRl1d_3T__13).
diagram_fact(synonym, cell_18, id_VDCRdWPJAwFapRl1d_3T__14).
diagram_fact(synonym, cell_19, id_VDCRdWPJAwFapRl1d_3T__15).
diagram_fact(synonym, cell_20, id_VDCRdWPJAwFapRl1d_3T__16).
diagram_fact(synonym, cell_21, id_VDCRdWPJAwFapRl1d_3T__17).
diagram_fact(synonym, cell_22, id_VDCRdWPJAwFapRl1d_3T__18).
diagram_fact(synonym, cell_4, id_0).
diagram_fact(synonym, cell_5, id_1).
diagram_fact(synonym, cell_6, id_VDCRdWPJAwFapRl1d_3T__2).
diagram_fact(synonym, cell_7, id_VDCRdWPJAwFapRl1d_3T__3).
diagram_fact(synonym, cell_8, id_VDCRdWPJAwFapRl1d_3T__4).
diagram_fact(synonym, cell_9, id_VDCRdWPJAwFapRl1d_3T__5).
diagram_fact(target, cell_10, id_VDCRdWPJAwFapRl1d_3T__10).
diagram_fact(target, cell_6, id_VDCRdWPJAwFapRl1d_3T__8).
diagram_fact(target, cell_7, id_VDCRdWPJAwFapRl1d_3T__11).
diagram_fact(target, cell_8, id_VDCRdWPJAwFapRl1d_3T__12).
diagram_fact(target, cell_9, id_VDCRdWPJAwFapRl1d_3T__9).
diagram_fact(value, cell_11, "#sequence").
diagram_fact(value, cell_12, "SaySomething").
diagram_fact(value, cell_13, "SaySomething2").
diagram_fact(value, cell_14, "SaySomething2").
diagram_fact(value, cell_15, "ThinkWhatToSay").
diagram_fact(value, cell_16, "SaySomething").
diagram_fact(value, cell_17, "message = &quot;SaySomething2 works too&quot;").
diagram_fact(value, cell_18, "text=&quot;{the_answer}&quot;").
diagram_fact(value, cell_19, "message=&quot;{the_answer}&quot;").
diagram_fact(value, cell_20, "message=&quot;{the_answer}&quot;").
diagram_fact(value, cell_21, "message = &quot;Start thinking...&quot;").
diagram_fact(value, cell_22, "&lt;div&gt;&lt;div&gt;&amp;lt;root main_tree_to_execute = &quot;MainTree&quot; &amp;gt;&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; &amp;lt;BehaviorTree ID=&quot;MainTree&quot;&amp;gt;&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&amp;lt;Sequence name=&quot;root_sequence&quot;&amp;gt;&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&amp;lt;SaySomething&amp;nbsp; &amp;nbsp; &amp;nbsp;message=&quot;start thinking...&quot; /&amp;gt;&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&amp;lt;ThinkWhatToSay&amp;nbsp; &amp;nbsp;text=&quot;{the_answer}&quot;/&amp;gt;&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&amp;lt;SaySomething&amp;nbsp; &amp;nbsp; &amp;nbsp;message=&quot;{the_answer}&quot; /&amp;gt;&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&amp;lt;SaySomething2&amp;nbsp; &amp;nbsp; message=&quot;SaySomething2 works too...&quot; /&amp;gt;&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&amp;lt;SaySomething2&amp;nbsp; &amp;nbsp; message=&quot;{the_answer}&quot; /&amp;gt;&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&amp;lt;/Sequence&amp;gt;&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; &amp;lt;/BehaviorTree&amp;gt;&lt;/div&gt;&lt;div&gt;&amp;lt;/root&amp;gt;&lt;/div&gt;&lt;/div&gt;&lt;div&gt;&lt;br style=&quot;&quot;&gt;&lt;/div&gt;").
diagram_fact(vertex, cell_11, 1).
diagram_fact(vertex, cell_12, 1).
diagram_fact(vertex, cell_13, 1).
diagram_fact(vertex, cell_14, 1).
diagram_fact(vertex, cell_15, 1).
diagram_fact(vertex, cell_16, 1).
diagram_fact(vertex, cell_17, 1).
diagram_fact(vertex, cell_18, 1).
diagram_fact(vertex, cell_19, 1).
diagram_fact(vertex, cell_20, 1).
diagram_fact(vertex, cell_21, 1).
diagram_fact(vertex, cell_22, 1).
diagram_fact(verticalAlign, cell_10, "top").
diagram_fact(verticalAlign, cell_11, "top").
diagram_fact(verticalAlign, cell_12, "top").
diagram_fact(verticalAlign, cell_13, "top").
diagram_fact(verticalAlign, cell_14, "top").
diagram_fact(verticalAlign, cell_15, "top").
diagram_fact(verticalAlign, cell_16, "top").
diagram_fact(verticalAlign, cell_6, "top").
diagram_fact(verticalAlign, cell_7, "top").
diagram_fact(verticalAlign, cell_8, "top").
diagram_fact(verticalAlign, cell_9, "top").
diagram_fact(whiteSpace, cell_11, "wrap").
diagram_fact(whiteSpace, cell_12, "wrap").
diagram_fact(whiteSpace, cell_13, "wrap").
diagram_fact(whiteSpace, cell_14, "wrap").
diagram_fact(whiteSpace, cell_15, "wrap").
diagram_fact(whiteSpace, cell_16, "wrap").
diagram_fact(whiteSpace, cell_17, "wrap").
diagram_fact(whiteSpace, cell_18, "wrap").
diagram_fact(whiteSpace, cell_19, "wrap").
diagram_fact(whiteSpace, cell_20, "wrap").
diagram_fact(whiteSpace, cell_21, "wrap").
diagram_fact(whiteSpace, cell_22, "wrap").
diagram_fact(width, cell_11, 240).
diagram_fact(width, cell_12, 160).
diagram_fact(width, cell_13, 170).
diagram_fact(width, cell_14, 160).
diagram_fact(width, cell_15, 140).
diagram_fact(width, cell_16, 180).
diagram_fact(width, cell_17, 150).
diagram_fact(width, cell_18, 120).
diagram_fact(width, cell_19, 140).
diagram_fact(width, cell_20, 140).
diagram_fact(width, cell_21, 150).
diagram_fact(width, cell_22, 390).
diagram_fact(x, cell_11, 440).
diagram_fact(x, cell_12, 440).
diagram_fact(x, cell_13, 660).
diagram_fact(x, cell_14, 870).
diagram_fact(x, cell_15, 240).
diagram_fact(x, cell_16, 10).
diagram_fact(x, cell_17, 670).
diagram_fact(x, cell_18, 250).
diagram_fact(x, cell_19, 450).
diagram_fact(x, cell_20, 877.5).
diagram_fact(x, cell_21, 25).
diagram_fact(x, cell_22, 120).
diagram_fact(y, cell_11, 50).
diagram_fact(y, cell_12, 200).
diagram_fact(y, cell_13, 200).
diagram_fact(y, cell_14, 200).
diagram_fact(y, cell_15, 200).
diagram_fact(y, cell_16, 200).
diagram_fact(y, cell_17, 235).
diagram_fact(y, cell_18, 240).
diagram_fact(y, cell_19, 240).
diagram_fact(y, cell_20, 240).
diagram_fact(y, cell_21, 235).
diagram_fact(y, cell_22, 360).
treefact(connected, cell_11, cell_12).
treefact(connected, cell_11, cell_13).
treefact(connected, cell_11, cell_14).
treefact(connected, cell_11, cell_15).
treefact(connected, cell_11, cell_16).
treefact(kind, cell_11, sequence).
treefact(kind, cell_12, syncnode).
treefact(kind, cell_13, syncnode).
treefact(kind, cell_14, syncnode).
treefact(kind, cell_15, syncnode).
treefact(kind, cell_16, syncnode).
treefact(kind, cell_17, textbox).
treefact(kind, cell_18, textbox).
treefact(kind, cell_19, textbox).
treefact(kind, cell_20, textbox).
treefact(kind, cell_21, textbox).
treefact(kind, cell_22, asyncnode).
treefact(name, cell_11, "#sequence").
treefact(name, cell_12, "SaySomething").
treefact(name, cell_13, "SaySomething2").
treefact(name, cell_14, "SaySomething2").
treefact(name, cell_15, "ThinkWhatToSay").
treefact(name, cell_16, "SaySomething").
treefact(name, cell_22, "&lt;div&gt;&lt;div&gt;&amp;lt;root main_tree_to_execute = &quot;MainTree&quot; &amp;gt;&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; &amp;lt;BehaviorTree ID=&quot;MainTree&quot;&amp;gt;&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&amp;lt;Sequence name=&quot;root_sequence&quot;&amp;gt;&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&amp;lt;SaySomething&amp;nbsp; &amp;nbsp; &amp;nbsp;message=&quot;start thinking...&quot; /&amp;gt;&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&amp;lt;ThinkWhatToSay&amp;nbsp; &amp;nbsp;text=&quot;{the_answer}&quot;/&amp;gt;&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&amp;lt;SaySomething&amp;nbsp; &amp;nbsp; &amp;nbsp;message=&quot;{the_answer}&quot; /&amp;gt;&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&amp;lt;SaySomething2&amp;nbsp; &amp;nbsp; message=&quot;SaySomething2 works too...&quot; /&amp;gt;&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&amp;lt;SaySomething2&amp;nbsp; &amp;nbsp; message=&quot;{the_answer}&quot; /&amp;gt;&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; &amp;nbsp; &amp;nbsp;&amp;lt;/Sequence&amp;gt;&lt;/div&gt;&lt;div&gt;&amp;nbsp; &amp;nbsp; &amp;lt;/BehaviorTree&amp;gt;&lt;/div&gt;&lt;div&gt;&amp;lt;/root&amp;gt;&lt;/div&gt;&lt;/div&gt;&lt;div&gt;&lt;br style=&quot;&quot;&gt;&lt;/div&gt;").
treefact(text, cell_17, "message = &quot;SaySomething2 works too&quot;").
treefact(text, cell_18, "text=&quot;{the_answer}&quot;").
treefact(text, cell_19, "message=&quot;{the_answer}&quot;").
treefact(text, cell_20, "message=&quot;{the_answer}&quot;").
treefact(text, cell_21, "message = &quot;Start thinking...&quot;").
