diagram_fact(as, cell_10, "geometry").
diagram_fact(as, cell_11, "geometry").
diagram_fact(as, cell_12, "geometry").
diagram_fact(as, cell_13, "geometry").
diagram_fact(as, cell_14, "geometry").
diagram_fact(as, cell_15, "geometry").
diagram_fact(as, cell_16, "geometry").
diagram_fact(as, cell_17, "geometry").
diagram_fact(as, cell_18, "geometry").
diagram_fact(as, cell_6, "geometry").
diagram_fact(as, cell_7, "geometry").
diagram_fact(as, cell_8, "geometry").
diagram_fact(as, cell_9, "geometry").
diagram_fact(cell, cell_10, "").
diagram_fact(cell, cell_11, "").
diagram_fact(cell, cell_12, "").
diagram_fact(cell, cell_13, "").
diagram_fact(cell, cell_14, "").
diagram_fact(cell, cell_15, "").
diagram_fact(cell, cell_16, "").
diagram_fact(cell, cell_17, "").
diagram_fact(cell, cell_18, "").
diagram_fact(cell, cell_4, "").
diagram_fact(cell, cell_5, "").
diagram_fact(cell, cell_6, "").
diagram_fact(cell, cell_7, "").
diagram_fact(cell, cell_8, "").
diagram_fact(cell, cell_9, "").
diagram_fact(curved, cell_11, 1).
diagram_fact(curved, cell_12, 1).
diagram_fact(curved, cell_6, 1).
diagram_fact(curved, cell_7, 1).
diagram_fact(curved, cell_8, 1).
diagram_fact(diagram, diagram_1, "").
diagram_fact(edge, cell_11, 1).
diagram_fact(edge, cell_12, 1).
diagram_fact(edge, cell_16, 1).
diagram_fact(edge, cell_6, 1).
diagram_fact(edge, cell_7, 1).
diagram_fact(edge, cell_8, 1).
diagram_fact(edgeStyle, cell_11, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_12, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_16, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_6, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_7, "orthogonalEdgeStyle").
diagram_fact(edgeStyle, cell_8, "orthogonalEdgeStyle").
diagram_fact(entryDx, cell_16, 0).
diagram_fact(entryDx, cell_6, 0).
diagram_fact(entryDx, cell_7, 0).
diagram_fact(entryDx, cell_8, 0).
diagram_fact(entryDy, cell_16, 0).
diagram_fact(entryDy, cell_6, 0).
diagram_fact(entryDy, cell_7, 0).
diagram_fact(entryDy, cell_8, 0).
diagram_fact(entryX, cell_16, 0.5).
diagram_fact(entryX, cell_6, 0.5).
diagram_fact(entryX, cell_7, 0.5).
diagram_fact(entryX, cell_8, 0.5).
diagram_fact(entryY, cell_16, 0).
diagram_fact(entryY, cell_6, 0).
diagram_fact(entryY, cell_7, 0).
diagram_fact(entryY, cell_8, 0).
diagram_fact(exitDx, cell_11, 0).
diagram_fact(exitDx, cell_12, 0).
diagram_fact(exitDx, cell_16, 0).
diagram_fact(exitDx, cell_6, 0).
diagram_fact(exitDx, cell_7, 0).
diagram_fact(exitDx, cell_8, 0).
diagram_fact(exitDy, cell_11, 0).
diagram_fact(exitDy, cell_12, 0).
diagram_fact(exitDy, cell_16, 0).
diagram_fact(exitDy, cell_6, 0).
diagram_fact(exitDy, cell_7, 0).
diagram_fact(exitDy, cell_8, 0).
diagram_fact(exitX, cell_11, 0.5).
diagram_fact(exitX, cell_12, 0.5).
diagram_fact(exitX, cell_16, 0.5).
diagram_fact(exitX, cell_6, 0.5).
diagram_fact(exitX, cell_7, 0.5).
diagram_fact(exitX, cell_8, 0.5).
diagram_fact(exitY, cell_11, 1).
diagram_fact(exitY, cell_12, 1).
diagram_fact(exitY, cell_16, 1).
diagram_fact(exitY, cell_6, 1).
diagram_fact(exitY, cell_7, 1).
diagram_fact(exitY, cell_8, 1).
diagram_fact(height, cell_10, 60).
diagram_fact(height, cell_13, 60).
diagram_fact(height, cell_14, 60).
diagram_fact(height, cell_15, 60).
diagram_fact(height, cell_17, 60).
diagram_fact(height, cell_18, 60).
diagram_fact(height, cell_9, 60).
diagram_fact(html, cell_10, 1).
diagram_fact(html, cell_11, 1).
diagram_fact(html, cell_12, 1).
diagram_fact(html, cell_13, 1).
diagram_fact(html, cell_14, 1).
diagram_fact(html, cell_15, 1).
diagram_fact(html, cell_16, 1).
diagram_fact(html, cell_17, 1).
diagram_fact(html, cell_18, 1).
diagram_fact(html, cell_6, 1).
diagram_fact(html, cell_7, 1).
diagram_fact(html, cell_8, 1).
diagram_fact(html, cell_9, 1).
diagram_fact(jettySize, cell_11, "auto").
diagram_fact(jettySize, cell_12, "auto").
diagram_fact(jettySize, cell_16, "auto").
diagram_fact(jettySize, cell_6, "auto").
diagram_fact(jettySize, cell_7, "auto").
diagram_fact(jettySize, cell_8, "auto").
diagram_fact(mxGraphModel, mxGraphModel_2, mxGraphModel_2).
diagram_fact(name, diagram_1, "tree").
diagram_fact(orthogonalLoop, cell_11, 1).
diagram_fact(orthogonalLoop, cell_12, 1).
diagram_fact(orthogonalLoop, cell_16, 1).
diagram_fact(orthogonalLoop, cell_6, 1).
diagram_fact(orthogonalLoop, cell_7, 1).
diagram_fact(orthogonalLoop, cell_8, 1).
diagram_fact(parent, cell_10, id_1).
diagram_fact(parent, cell_11, id_1).
diagram_fact(parent, cell_12, id_1).
diagram_fact(parent, cell_13, id_1).
diagram_fact(parent, cell_14, id_1).
diagram_fact(parent, cell_15, id_1).
diagram_fact(parent, cell_16, id_1).
diagram_fact(parent, cell_17, id_1).
diagram_fact(parent, cell_18, id_1).
diagram_fact(parent, cell_5, id_0).
diagram_fact(parent, cell_6, id_1).
diagram_fact(parent, cell_7, id_1).
diagram_fact(parent, cell_8, id_1).
diagram_fact(parent, cell_9, id_1).
diagram_fact(relative, cell_11, 1).
diagram_fact(relative, cell_12, 1).
diagram_fact(relative, cell_16, 1).
diagram_fact(relative, cell_6, 1).
diagram_fact(relative, cell_7, 1).
diagram_fact(relative, cell_8, 1).
diagram_fact(root, root_3, root_3).
diagram_fact(rounded, cell_10, 1).
diagram_fact(rounded, cell_13, 1).
diagram_fact(rounded, cell_14, 1).
diagram_fact(rounded, cell_15, 1).
diagram_fact(rounded, cell_16, 0).
diagram_fact(rounded, cell_17, 1).
diagram_fact(rounded, cell_18, 1).
diagram_fact(rounded, cell_9, 1).
diagram_fact(source, cell_11, bmLo2S3h3X6idPI3VYxt__9).
diagram_fact(source, cell_12, bmLo2S3h3X6idPI3VYxt__9).
diagram_fact(source, cell_16, bmLo2S3h3X6idPI3VYxt__12).
diagram_fact(source, cell_6, bmLo2S3h3X6idPI3VYxt__1).
diagram_fact(source, cell_7, bmLo2S3h3X6idPI3VYxt__1).
diagram_fact(source, cell_8, bmLo2S3h3X6idPI3VYxt__1).
diagram_fact(synonym, cell_10, bmLo2S3h3X6idPI3VYxt__8).
diagram_fact(synonym, cell_11, bmLo2S3h3X6idPI3VYxt__17).
diagram_fact(synonym, cell_12, bmLo2S3h3X6idPI3VYxt__18).
diagram_fact(synonym, cell_13, bmLo2S3h3X6idPI3VYxt__9).
diagram_fact(synonym, cell_14, bmLo2S3h3X6idPI3VYxt__10).
diagram_fact(synonym, cell_15, bmLo2S3h3X6idPI3VYxt__11).
diagram_fact(synonym, cell_16, id_XUyjzxSoE4rl8wdpkgez__1).
diagram_fact(synonym, cell_17, bmLo2S3h3X6idPI3VYxt__12).
diagram_fact(synonym, cell_18, bmLo2S3h3X6idPI3VYxt__13).
diagram_fact(synonym, cell_4, id_0).
diagram_fact(synonym, cell_5, id_1).
diagram_fact(synonym, cell_6, bmLo2S3h3X6idPI3VYxt__14).
diagram_fact(synonym, cell_7, bmLo2S3h3X6idPI3VYxt__15).
diagram_fact(synonym, cell_8, bmLo2S3h3X6idPI3VYxt__16).
diagram_fact(synonym, cell_9, bmLo2S3h3X6idPI3VYxt__1).
diagram_fact(target, cell_11, bmLo2S3h3X6idPI3VYxt__11).
diagram_fact(target, cell_12, bmLo2S3h3X6idPI3VYxt__12).
diagram_fact(target, cell_16, bmLo2S3h3X6idPI3VYxt__13).
diagram_fact(target, cell_6, bmLo2S3h3X6idPI3VYxt__8).
diagram_fact(target, cell_7, bmLo2S3h3X6idPI3VYxt__9).
diagram_fact(target, cell_8, bmLo2S3h3X6idPI3VYxt__10).
diagram_fact(value, cell_10, "Open Fridge").
diagram_fact(value, cell_13, "#fallback").
diagram_fact(value, cell_14, "Close Fridge").
diagram_fact(value, cell_15, "Grab beer").
diagram_fact(value, cell_17, "Force Failure").
diagram_fact(value, cell_18, "Close Fridge").
diagram_fact(value, cell_9, "#sequence").
diagram_fact(vertex, cell_10, 1).
diagram_fact(vertex, cell_13, 1).
diagram_fact(vertex, cell_14, 1).
diagram_fact(vertex, cell_15, 1).
diagram_fact(vertex, cell_17, 1).
diagram_fact(vertex, cell_18, 1).
diagram_fact(vertex, cell_9, 1).
diagram_fact(whiteSpace, cell_10, "wrap").
diagram_fact(whiteSpace, cell_13, "wrap").
diagram_fact(whiteSpace, cell_14, "wrap").
diagram_fact(whiteSpace, cell_15, "wrap").
diagram_fact(whiteSpace, cell_17, "wrap").
diagram_fact(whiteSpace, cell_18, "wrap").
diagram_fact(whiteSpace, cell_9, "wrap").
diagram_fact(width, cell_10, 120).
diagram_fact(width, cell_13, 120).
diagram_fact(width, cell_14, 120).
diagram_fact(width, cell_15, 120).
diagram_fact(width, cell_17, 120).
diagram_fact(width, cell_18, 120).
diagram_fact(width, cell_9, 120).
diagram_fact(x, cell_10, 160).
diagram_fact(x, cell_13, 360).
diagram_fact(x, cell_14, 560).
diagram_fact(x, cell_15, 260).
diagram_fact(x, cell_17, 460).
diagram_fact(x, cell_18, 460).
diagram_fact(x, cell_9, 360).
diagram_fact(y, cell_10, 240).
diagram_fact(y, cell_13, 240).
diagram_fact(y, cell_14, 240).
diagram_fact(y, cell_15, 395).
diagram_fact(y, cell_17, 395).
diagram_fact(y, cell_18, 520).
diagram_fact(y, cell_9, 80).
